
cms:
  build: hub.srv.webeye.services:5000/public/django-cms:0.0.1 
  ports:
    - '8000'
  environment:
    # tell HTTPS-PORTAL to set up "example.com"
    VIRTUAL_HOST_INTERNAL: test01.webeye.services
    VIRTUAL_PORT: '8000'
  links:
    - "db:db"


db:
  image: postgres:9
  environment:
   - POSTGRES_PASSWORD=2a@aab2bb1
   - POSTGRES_DB=webeye_web

https-portal:
  image: wsrak/nginx-proxy-internal:latest
  links:
    - cms:cms
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /home/rak/PycharmProjects/docker-webeyes/Docker/ssl_certs:/var/lib/https-portal
  extra_hosts:
    - "webeye.services: 127.0.0.1"

  #environment:
    # FORCE_RENEW: 'true'
    
